name: dartcarwings
description: A library for the Nissan Leaf Carwings API.
version: 1.0.1
homepage: https://gitlab.com/tobiaswkjeldsen/dartcarwings
author: Tobias Westergaard Kjeldsen <tobias@wkjeldsen.dk>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: '^0.17.0'
  http: '^0.13.1'
  blowfish_ecb: '^0.1.0'

dev_dependencies:
  test: '^1.3.0'
