name: dartcarwings
description: A library for the Nissan Leaf Carwings API.
version: 1.0.0
homepage: https://gitlab.com/tobiaswkjeldsen/dartcarwings

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: '^0.17.0'
  http: '^0.13.1'
  pointycastle: ^4.0.0

dev_dependencies:
  test: '^1.3.0'
